app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@ApiBundle/Controller/V1"
    type:     annotation
    prefix:   /api/v1

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# FOSOAuthServerBundle routes
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"